services:
  camel-hl7-simulator:
    build:
      context: ./project
      dockerfile: Dockerfile
      target: run
    image: camel-hl7-simulator:latest
    ports:
      - "${EXTERNAL_PORT:-8081}:${APP_PORT:-8080}"
    environment:
      - APP_PORT=${APP_PORT:-8080}
      - SCHEDULER_ENABLED=${SCHEDULER_ENABLED:-false}
    volumes:
      - ./project/output:/app/output
    depends_on:
      - build

  build:
    build:
      context: ./project
      dockerfile: Dockerfile
      target: build
    image: camel-hl7-simulator-build:latest
    volumes:
      - ./project/target:/app/target
    command: mvn clean package

networks:
  default:
    name: camel-hl7-network
