services:
  camel-hl7-simulator:
    build:
      context: ./project
      dockerfile: Dockerfile
    image: camel-hl7-simulator:latest
    ports:
      - "${EXTERNAL_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      - APP_PORT=${APP_PORT:-8080}
      - SCHEDULER_ENABLED=${SCHEDULER_ENABLED:-false}
    volumes:
      - ./project/output:/app/output
    networks:
      - camel-hl7-network

networks:
  camel-hl7-network:
    driver: bridge
